<?php

namespace SystemUsersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResourcesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourcesRepository extends EntityRepository
{

    public function getRolesName($data)
    {
        $em = $this->getEntityManager()->getConnection();

        $sql = "SELECT 
                    roles.role_name
                FROM
                    (gw_dgdp_demo.roles roles
                    INNER JOIN roleresource roleresource ON (roles.id = roleresource.role_id))
                        INNER JOIN
                    resources resources ON (resources.id = roleresource.resource_id)
                WHERE
                    (resources.controller_name = 'Users') AND (resources.action_name = 'create')";

        try {
            $result = $em->query($sql)->fetchAll();

            foreach ($result as $key => $value) {
                $role[$key] = $value['role_name'];
            }
//            echo "<pre>";
//            print_r($role);
//            die();
            return $role[0];
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
