<?php

namespace SystemUsersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoleResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleResourceRepository extends EntityRepository
{
}
