<?php

namespace SystemUsersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMetaRepository extends EntityRepository
{

    public function showApplication($id)
    {
        $em = $this->getEntityManager()->getConnection();

        $education = $this->getEntityManager()->getRepository('SporshoUserBundle:Education');

        $sql = "SELECT 
                    users.id,
                    users.slug,
                    users.email,
                    users.app_status,
                    users.roles,
                    um.father_name,
                    um.mother_name,
                    um.date_of_birth,
                    um.last_education,
                    um.national_id,
                    um.present_address,
                    um.permanent_address,
                    um.mobile_no,
                    um.image,
                    um.name,
                    um.job_status,
                    job.full_name AS job_location,
                    pre_dis.full_name AS pre_dis_name,
                    pre_dis.short_name AS pre_dis_short,
                    pre_ps.full_name AS pre_ps_name,
                    pre_dis.short_name AS pre_ps_short,
                    per_dis.full_name AS per_dis_name,
                    per_dis.short_name AS per_dis_short,
                    per_dis.full_name AS per_ps_name,
                    per_dis.short_name AS per_ps_short
                FROM
                    user_meta um
                        INNER JOIN
                    users users ON (um.user_id = users.id)
                        LEFT JOIN
                    districts pre_dis ON (um.present_district = pre_dis.id)
                        LEFT JOIN
                    police_station pre_ps ON (um.present_police_station = pre_ps.id)
                        LEFT JOIN
                    districts per_dis ON (um.permanent_district = per_dis.id)
                        LEFT JOIN
                    police_station per_ps ON (um.permanent_police_station = per_ps.id)
                       LEFT JOIN
                    districts job ON (um.job_location= job.id)
                 WHERE
                    (users.id = $id)
                 ORDER BY users.id DESC";

        try {
            $result = $em->query($sql)->fetch();

            if (!empty($result)) {
                $result['education'] = $education->getAllEducationInfo($id);
            }

            return $result;
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
