system_users_roles:
    resource: "@SystemUsersBundle/Resources/config/routing/roles.yml"
    prefix:   /roles

system_users_resources:
    resource: "@SystemUsersBundle/Resources/config/routing/resources.yml"
    prefix:   /resources

system_users_users:
    resource: "@SystemUsersBundle/Resources/config/routing/users.yml"
    prefix:   /users

#Security related portions

_login:
    path:     /login
    defaults: { _controller: SystemUsersBundle:Security:login }
    methods: GET
    
_login_check:
    path:     /login_check
    defaults: { _controller: SystemUsersBundle:Security:loginCheck }
    methods: POST
    
_logout:
    path:     /logout
    defaults: { _controller: SystemUsersBundle:Security:logout }
    methods: GET

change_passowrd:
    path:     /change_passowrd
    defaults: { _controller: SystemUsersBundle:Security:logout }
    methods: GET
    
_dashboard:
    path: /
    defaults: { _controller: SystemUsersBundle:Security:secureDashboard}
    methods: GET
