system_users_users:
    resource: "@SystemUsersBundle/Resources/config/routing/users.yml"
    prefix:   /users


personal_daily_cost_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SporshoDailyCostBundle:Default:index }
    
#user_registration:
#    resource: "@SystemUsersBundle/Resources/config/routing/registration.yml"
#    prefix:   /

    
UserBundle_usermeta:
    resource: "@SystemUsersBundle/Resources/config/routing/usersmeta.yml"
    prefix:   /usermeta

dashboard:
    resource: "@SystemUsersBundle/Resources/config/routing/dashboard.yml"
    prefix:   /


#Security related portions

_login:
    path:     /login
    defaults: { _controller: SystemUsersBundle:Security:login }
    methods: GET
    
_login_check:
    path:     /login_check
    defaults: { _controller: SystemUsersBundle:Security:loginCheck }
    methods: POST
    
_logout:
    path:     /logout
    defaults: { _controller: SystemUsersBundle:Security:logout }
    methods: GET

change_passowrd:
    path:     /change_passowrd
    defaults: { _controller: SystemUsersBundle:Security:logout }
    methods: GET
    
_dashboard:
    path: /
    defaults: { _controller: SystemUsersBundle:Security:secureDashboard}
    methods: GET
