SystemUsersBundle\Entity\User:
    properties:
     

#---------------------------------- Usermeta validation ----------------------------------------#
SystemUsersBundle\Entity\UserMeta:
    properties:
        name:
            - NotBlank: ~
        fatherName:
            - NotBlank: ~
            
SystemUsersBundle\Entity\Users:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: username
            message: "Username already exists"
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: email
            message: "Email already exists"

            