SystemUsersBundle\Entity\User:
    properties:
     

#---------------------------------- Usermeta validation ----------------------------------------#
SystemUsersBundle\Entity\UserMeta:
    properties:
        name:
            - NotBlank: ~
        fatherName:
            - NotBlank: ~

#---------------------------------- Users Entity Validation ----------------------------------------#
SystemUsersBundle\Entity\Users:
    properties:
        name:
            - NotBlank: 
                message: error
        username:
            - NotBlank: ~    
        
            