acme_demo_tag:
    resource: "@AcmeDemoBundle/Resources/config/routing/tag.yml"
    prefix:   /tag

acme_demo_task:
    resource: "@AcmeDemoBundle/Resources/config/routing/task.yml"
    prefix:   /task

_welcome:
    path:     /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo
